site_name: LLM Math Solver Docs

theme:
  name: "material"
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [ eval ]

nav:
  - Index: index.md
  - SFT: llm_sft.md
  - Evaluation:
      - GSM8K Eval: gsm8k_eval.md
      - MATH Eval: MATH_eval.md
